# for Trilinos TriBITS build system

set(LIB_REQUIRED_DEP_PACKAGES Kokkos)

set(LIB_OPTIONAL_DEP_PACKAGES) # no optional dependencies
set(LIB_REQUIRED_DEP_TPLS)
set(LIB_OPTIONAL_DEP_TPLS) # no optional TPLs
set(TEST_REQUIRED_DEP_PACKAGES)
set(TEST_OPTIONAL_DEP_PACKAGES)
set(TEST_REQUIRED_DEP_TPLS)
set(TEST_OPTIONAL_DEP_TPLS)