# for Trilinos TriBITS build system

set(LIB_REQUIRED_DEP_PACKAGES Kokkos) # we require Kokkos
set(LIB_OPTIONAL_DEP_PACKAGES)

set(TEST_REQUIRED_DEP_PACKAGES)
set(TEST_OPTIONAL_DEP_PACKAGES)

set(LIB_REQUIRED_DEP_TPLS)
set(LIB_OPTIONAL_DEP_TPLS MPI) # Optionally require MPI

set(TEST_REQUIRED_DEP_TPLS)
set(TEST_OPTIONAL_DEP_TPLS)