function(kc_add_unit_test name)
  # gersemi: hints { FILES: command_line, OPTIONS: command_line, INCLUDES: command_line, LIBRARIES: command_line }
  set(options CORE MPI NCCL)
  set(oneValueArgs NUM_PES)
  set(multiValueArgs FILES OPTIONS INCLUDES LIBRARIES)
  cmake_parse_arguments(UT "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  add_executable(${name})
  target_sources(${name} PRIVATE ${UT_FILES})
  target_compile_features(${name} PRIVATE cxx_std_20)
  target_compile_options(${name} PRIVATE ${UT_OPTIONS})
  target_include_directories(${name} PRIVATE ${UT_INCLUDES})
  target_link_libraries(${name} PRIVATE gtest fmt::fmt ${UT_LIBRARIES})

  if(UT_CORE)
    target_link_libraries(${name} PRIVATE KokkosComm::KokkosComm MPI::MPI_CXX)
    if(KokkosComm_ENABLE_NCCL)
      target_sources(${name} PRIVATE nccl/utils.cpp)
      target_link_libraries(${name} PRIVATE NCCL::NCCL)
    endif()
  elseif(UT_MPI)
    target_link_libraries(${name} PRIVATE MPI::MPI_CXX)
  elseif(UT_NCCL)
    target_link_libraries(${name} PRIVATE NCCL::NCCL)
  endif()

  add_test(NAME ${name} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${UT_NUM_PES} ./${name})
endfunction()

function(kc_add_perf_test name)
  # gersemi: hints { FILES: command_line, OPTIONS: command_line, INCLUDES: command_line, LIBRARIES: command_line }
  set(options CORE MPI NCCL)
  set(oneValueArgs NUM_PES)
  set(multiValueArgs FILES OPTIONS INCLUDES LIBRARIES)
  cmake_parse_arguments(PT "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  add_executable(${name})
  target_sources(${name} PRIVATE ${PT_FILES})
  target_compile_features(${name} PRIVATE cxx_std_20)
  target_compile_options(${name} PRIVATE ${PT_OPTIONS})
  target_include_directories(${name} PRIVATE ${PT_INCLUDES})
  target_link_libraries(${name} PRIVATE benchmark::benchmark fmt::fmt ${PT_LIBRARIES})

  if(PT_CORE)
    target_link_libraries(${name} PRIVATE KokkosComm::KokkosComm MPI::MPI_CXX)
    if(KokkosComm_ENABLE_NCCL)
      target_sources(${name} PRIVATE ../unit_tests/nccl/utils.cpp)
      target_link_libraries(${name} PRIVATE NCCL::NCCL)
    endif()
  elseif(PT_MPI)
    target_link_libraries(${name} PRIVATE MPI::MPI_CXX)
  elseif(PT_NCCL)
    target_link_libraries(${name} PRIVATE NCCL::NCCL)
  endif()

  add_test(NAME ${name} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${PT_NUM_PES} ./${name})
endfunction()
